"""E3 pack ``e3-synth-rooms``: dry FLEURS lines + a reference line convolved with a synthetic room.

Synthetic RIRs (numpy, seeded): a direct impulse, 4–10 sparse early reflections in 3–40 ms and a
late tail of Gaussian noise under a three-band exponential decay (high band decays faster). T60
spans 0.2–1.2 s and DRR −3…+12 dB by design; the *measured* T60/DRR/C50 of each RIR (the same
functions the E3 judge applies to its deconvolved estimate) are the references.
"""
from __future__ import annotations

import random
from pathlib import Path
from typing import Any

from .. import paths
from ..specs.e3 import rir_params
from . import builder
from .e_common import fleurs_utterances, merge_pack, read_mono

SR = 16000

LICENSE = """# E3 synthetic room matching ({lang})

Speech: google/fleurs test split (CC BY 4.0). Rooms: synthetic impulse responses generated by
bench/arena/builders/e3_rooms.py (seeded; no recorded RIRs). Eval use.
Groups: the dry line's FLoRes sentence id.
"""


def synth_rir(t60: float, drr_db: float, sr: int = SR, seed: int = 0):
    """Direct path + early reflections + 3-band exponentially decaying noise tail."""
    import numpy as np
    from scipy.signal import butter, sosfilt

    rng = np.random.default_rng(seed)
    n = int(min(2.0, 1.5 * t60 + 0.1) * sr)
    t = np.arange(n) / sr
    d0 = int(0.002 * sr)
    tail = np.zeros(n)
    edges = [(None, 500.0, 1.15), (500.0, 4000.0, 1.0), (4000.0, None, 0.7)]
    for lo, hi, scale in edges:
        noise = rng.normal(0, 1, n)
        if lo is None:
            sos = butter(4, hi, "lowpass", fs=sr, output="sos")
        elif hi is None:
            sos = butter(4, min(lo, sr / 2 - 100), "highpass", fs=sr, output="sos")
        else:
            sos = butter(4, [lo, hi], "bandpass", fs=sr, output="sos")
        tail += sosfilt(sos, noise) * np.exp(-6.9078 * t / (t60 * scale))
    onset = np.clip((t - 0.002) / 0.004, 0, 1)                 # tail builds up after 2 ms
    tail *= onset
    early = np.zeros(n)
    for _ in range(rng.integers(4, 11)):
        k = d0 + int(rng.uniform(0.003, 0.040) * sr)
        if k < n:
            early[k] += rng.uniform(0.15, 0.6) * rng.choice([-1, 1])
    rev = early + tail
    rev_e = float(np.sum(rev[d0 + int(0.0025 * sr) + 1:] ** 2))
    h = rev * np.sqrt(10 ** (-drr_db / 10) / max(rev_e, 1e-20))
    h[d0] += 1.0
    return h / np.max(np.abs(h))


@builder("e3-synth-rooms", capabilities=["E3"], langs=["en", "hi", "ja"], license="CC BY 4.0")
def e3_synth_rooms(lang: str, n: int | None = 150, seed: int = 0) -> Path:
    """E3 pack: dry FLEURS line + another line in a synthetic room (T60 0.2–1.2 s)."""
    import numpy as np
    import soundfile as sf
    from scipy.signal import fftconvolve

    rng = random.Random(seed)
    utts = fleurs_utterances(lang, 2 * (n or 150), seed=seed + 1)
    root = paths.eval_dir() / "E3" / lang
    for d in ("dry", "reference", "rir"):
        (root / d).mkdir(parents=True, exist_ok=True)
    rows: list[dict[str, Any]] = []
    for k in range(0, len(utts) - 1, 2):
        dry_u, ref_u = utts[k], utts[k + 1]
        t60, drr = rng.uniform(0.2, 1.2), rng.uniform(-3.0, 12.0)
        rid = f"room{k // 2:04d}"
        h = synth_rir(t60, drr, SR, seed=seed * 100003 + k)
        truth = rir_params(h, SR)
        dry, _ = read_mono(dry_u["path"], SR)
        ref, _ = read_mono(ref_u["path"], SR)
        wet = fftconvolve(ref, h)[: len(ref) + int(0.5 * SR)]
        wet *= np.sqrt(np.mean(ref ** 2) / max(np.mean(wet ** 2), 1e-20))
        peak = float(np.max(np.abs(wet)))
        if peak > 0.99:
            wet *= 0.99 / peak
        sf.write(root / "dry" / f"{dry_u['id']}.wav", dry, SR, subtype="PCM_16")
        sf.write(root / "reference" / f"{rid}.wav", wet, SR, subtype="PCM_16")
        sf.write(root / "rir" / f"{rid}.wav", h, SR, subtype="FLOAT")
        rows.append({"id": f"e3-{rid}-{dry_u['id']}", "group": dry_u["group"], "split": "test",
                     "inputs": {"audio": f"dry/{dry_u['id']}.wav",
                                "reference": f"reference/{rid}.wav"},
                     "refs": {"rir": f"rir/{rid}.wav", "text": dry_u["text"],
                              **{k2: round(v, 4) for k2, v in truth.items()}},
                     "meta": {"duration_s": round(len(dry) / SR, 3),
                              "design": {"t60_s": round(t60, 3), "drr_db": round(drr, 2)}}})
        if n and len(rows) >= n:
            break
    return merge_pack("E3", lang, rows, LICENSE.format(lang=lang), "synth-rooms")
