"""E4 packs: dub programmes (dialogue stem + M&E bed) × delivery presets.

A *programme* is 6–10 dialogue lines placed on a timeline over a synthetic bed (filtered noise
ambience with a slow LFO, a swelling chord pad and short effect bursts in the gaps; numpy,
seeded). Each programme exists twice:

- the **original**: reference lines at expressive levels (±4 LU around −26 LUFS) over the bed at a
  dialogue-over-bed ratio of 6–14 dB; its per-line levels and speech/bed balance are the refs;
- the **dub**: different lines in the same slots with TTS-like level errors (a global −10…+4 dB
  offset and ±6 dB per line) over the same bed — the candidate's input, exactly what the app's
  mix stage gets (dub vocals, background, the separated original dialogue as reference).

Every programme becomes four items, one per delivery preset (web −16, EBU R128 −23,
ATSC A/85 −24, Netflix −27 dialogue-gated), grouped by programme.

- ``e4-fleurs-programmes``: dub and reference lines are FLEURS utterances (CC BY 4.0).
- ``e4-arena-programmes``: dub lines are arena outputs of a voice capability (D1 by default); the
  reference lines are the items' source lines when the pack marks them (``meta.src_audio`` or
  ``meta.ref_is_source_line``), else the line/balance refs are omitted.
"""
from __future__ import annotations

import math
import random
from pathlib import Path
from typing import Any

from .. import paths
from ..specs.e1 import speech_intervals
from ..specs.e4 import DELIVERIES, speech_bed_db, window_loudness
from . import builder
from .e_common import arena_outputs, fleurs_utterances, merge_pack, read_mono

SR = 48000
ANCHOR_LUFS = -26.0

FLEURS_LICENSE = """# E4 synthetic dub programmes ({lang})

Dialogue: google/fleurs test split (CC BY 4.0). Bed: synthetic (numpy, seeded). Level errors,
placements and balance are generated by bench/arena/builders/e4_programmes.py. Eval use.
Groups: programme (its four delivery presets share one group).
"""
ARENA_LICENSE = """# E4 dub programmes from arena outputs ({capability}, {lang})

Dialogue lines are outputs of arena candidates for {capability} (licences follow the generating
model); bed synthetic. Eval-only, never redistributed.
"""


def _trim(x, sr: int):
    sp = speech_intervals(x, sr)
    if not sp:
        return x
    return x[max(0, int((sp[0][0] - 0.05) * sr)):int((sp[-1][1] + 0.05) * sr)]


def _set_loudness(x, target: float):
    lk = window_loudness(x, SR, 0.0, len(x) / SR)
    return x * 10 ** ((target - lk) / 20) if math.isfinite(lk) else x


def synth_bed(n: int, gaps: list[list[float]], rng):
    """Stereo bed: ambience + pad + effect bursts (float64, arbitrary level)."""
    import numpy as np
    from scipy.signal import butter, sosfilt

    t = np.arange(n) / SR
    amb = np.stack([sosfilt(butter(2, [120, 6000], "bandpass", fs=SR, output="sos"),
                            rng.normal(0, 1, n)) for _ in range(2)], 1)
    amb *= (0.7 + 0.3 * np.sin(2 * np.pi * rng.uniform(0.05, 0.2) * t))[:, None]
    root = rng.uniform(110, 220)
    pad = sum(np.sin(2 * np.pi * root * r * t * (1 + 0.002 * np.sin(2 * np.pi * 5 * t)))
              for r in (1.0, 1.26, 1.5))
    swell = 0.5 + 0.5 * np.sin(2 * np.pi * t / rng.uniform(8, 20) + rng.uniform(0, 6.28))
    bed = amb * 0.5 + (pad * swell)[:, None] * np.array([0.3, 0.25])
    for s, e in gaps:
        if e - s > 0.6 and rng.random() < 0.5:
            k0 = int((s + rng.uniform(0.1, e - s - 0.4)) * SR)
            k1 = min(n, k0 + int(0.25 * SR))
            burst = rng.normal(0, 1, k1 - k0) * np.exp(-np.linspace(0, 6, k1 - k0))
            bed[k0:k1] += (burst * 2.0)[:, None]
    return bed


def assemble(dub_lines: list, ref_lines: list | None, rng) -> dict[str, Any]:
    """Place lines, set levels, build bed; returns arrays + speech intervals + refs."""
    import numpy as np

    from ..specs.e4 import complement

    t, speech, placed = rng.uniform(0.8, 2.0), [], []
    for i, dub in enumerate(dub_lines):
        ref = ref_lines[i] if ref_lines else None
        slot = max(len(dub), len(ref) if ref is not None else 0) / SR
        speech.append([round(t, 3), round(t + slot, 3)])
        placed.append((t, dub, ref))
        t += slot + rng.uniform(0.6, 3.0)
    total = t + rng.uniform(0.5, 1.5)
    n = int(total * SR)
    dub_st, ref_st = np.zeros((n, 2)), np.zeros((n, 2))
    offset = rng.uniform(-10.0, 4.0)
    rels = []
    for t0, dub, ref in placed:
        k = int(t0 * SR)
        rel = rng.uniform(-4.0, 4.0)
        rels.append(rel)
        d = _set_loudness(dub, ANCHOR_LUFS + rel + offset + rng.uniform(-6.0, 6.0))
        dub_st[k:k + len(d)] += d[:, None]
        if ref is not None:
            r = _set_loudness(ref, ANCHOR_LUFS + rel)
            ref_st[k:k + len(r)] += r[:, None]
    bed = synth_bed(n, complement(speech, total, pad=0.0), rng)
    dbr = rng.uniform(6.0, 14.0)
    bed_l = window_loudness(bed, SR, 0.0, total)
    bed *= 10 ** ((ANCHOR_LUFS - dbr - bed_l) / 20)
    premix, original = dub_st + bed, ref_st + bed
    scale = 0.9 / max(1e-9, float(np.max(np.abs(premix))), float(np.max(np.abs(original))), 0.9)
    out = {"dialogue": dub_st * scale, "background": bed * scale, "premix": premix * scale,
           "speech": speech, "duration_s": round(total, 3), "offset_db": round(offset, 2),
           "dbr_db": round(dbr, 2)}
    if ref_lines:
        original *= scale
        out["reference_dialogue"] = ref_st * scale
        out["lines"] = [[s, e, round(window_loudness(original, SR, s, e), 3)] for s, e in speech]
        out["speech_bed_db"] = speech_bed_db(original, SR, speech)
    return out


def _write_programme(root: Path, pid: str, prog: dict[str, Any], group: str,
                     extra_meta: dict[str, Any]) -> list[dict[str, Any]]:
    import soundfile as sf

    d = root / "programmes" / pid
    d.mkdir(parents=True, exist_ok=True)
    inputs: dict[str, Any] = {"speech": prog["speech"]}
    for key, name in (("dialogue", "dialogue"), ("background", "background"),
                      ("premix", "audio"), ("reference_dialogue", "reference_dialogue")):
        if key in prog:
            sf.write(d / f"{key}.wav", prog[key], SR, subtype="PCM_24")
            inputs[name] = f"programmes/{pid}/{key}.wav"
    rows = []
    for dkey, delivery in DELIVERIES.items():
        refs: dict[str, Any] = {"speech": prog["speech"], "delivery": delivery}
        if "lines" in prog:
            refs["lines"] = prog["lines"]
            refs["speech_bed_db"] = prog["speech_bed_db"]
        rows.append({"id": f"{pid}-{dkey}", "group": group, "split": "test",
                     "inputs": {**inputs, "delivery": delivery}, "refs": refs,
                     "meta": {"duration_s": prog["duration_s"], "offset_db": prog["offset_db"],
                              "dbr_db": prog["dbr_db"], "delivery": dkey, **extra_meta}})
    return rows


@builder("e4-fleurs-programmes", capabilities=["E4"], langs=["en", "hi", "ja"],
         license="CC BY 4.0")
def e4_fleurs_programmes(lang: str, n: int | None = 40, seed: int = 0) -> Path:
    """E4 pack: n synthetic dub programmes (FLEURS lines over a synthetic bed) × 4 deliveries."""
    import numpy as np

    rng = np.random.default_rng(seed)
    pick = random.Random(seed)
    n = n or 40
    utts = fleurs_utterances(lang, n * 20, seed=seed + 2)
    root = paths.eval_dir() / "E4" / lang
    rows: list[dict[str, Any]] = []
    pos = 0
    for p in range(n):
        k = pick.randint(6, 10)
        if pos + 2 * k > len(utts):
            break
        chunk, pos = utts[pos:pos + 2 * k], pos + 2 * k
        dub = [_trim(read_mono(u["path"], SR)[0], SR) for u in chunk[:k]]
        ref = [_trim(read_mono(u["path"], SR)[0], SR) for u in chunk[k:]]
        prog = assemble(dub, ref, rng)
        rows += _write_programme(root, f"prog{p:03d}", prog, f"prog{p:03d}", {})
    return merge_pack("E4", lang, rows, FLEURS_LICENSE.format(lang=lang), "fleurs-programmes")


@builder("e4-arena-programmes", capabilities=["E4"], langs=["en", "hi", "ja"],
         license="per generating model")
def e4_arena_programmes(lang: str, n: int | None = 20, capability: str = "D1",
                        candidates: list[str] | None = None, lines: int = 8,
                        seed: int = 0) -> Path:
    """E4 pack: programmes built from arena voice outputs (default D1) × 4 deliveries."""
    import numpy as np

    rng = np.random.default_rng(seed)
    by_cand: dict[str, list[dict[str, Any]]] = {}
    for o in arena_outputs(capability, lang, candidates):
        by_cand.setdefault(o["candidate"], []).append(o)
    root = paths.eval_dir() / "E4" / lang
    rows: list[dict[str, Any]] = []
    count = 0
    for cand, outs in sorted(by_cand.items()):
        for c0 in range(0, len(outs) - lines + 1, lines):
            chunk = outs[c0:c0 + lines]
            dub = [_trim(read_mono(o["audio"], SR)[0], SR) for o in chunk]
            refs = []
            for o in chunk:
                it = o["item"]
                src = it.meta.get("src_audio") or (it.inputs.get("ref_audio")
                                                   if it.meta.get("ref_is_source_line") else None)
                refs.append(_trim(read_mono(src, SR)[0], SR)
                            if src and Path(str(src)).exists() else None)
            ref_lines = refs if all(r is not None for r in refs) else None
            prog = assemble(dub, ref_lines, rng)
            pid = f"arena-{capability}-{cand}-{c0 // lines:03d}"
            rows += _write_programme(root, pid, prog, pid,
                                     {"from": capability, "candidate": cand})
            count += 1
            if n and count >= n:
                break
        if n and count >= n:
            break
    return merge_pack("E4", lang, rows, ARENA_LICENSE.format(capability=capability, lang=lang),
                      f"arena-{capability}")
